---
title: "STAT184 Project"
author: "ProjectTeam6-3"
date: "4/20/2021"
output: html_notebook
---
### Load Packages
```{r}
library(tidyverse)
library(tidyr)
```
### Read Data
```{r}
MemorialFantasy <-
  read_csv("Memorial_Fantasy.csv")
SchwabFantasy <-
  read_csv("Schwab_Fantasy.csv")
PGAFantasy <-
  read_csv("PGA_Fantasy.csv")
```

```{r}
MemorialStats <-
  read.table(file ="Memorial_Stats.txt", header = FALSE,sep = "\n",dec = ".", skip = 1)

MemorialStats <- as.data.frame(matrix(MemorialStats$V1[MemorialStats$V1!=""], ncol = 9, byrow = TRUE))

names(MemorialStats) <- c("Position","Player", "Score","Putt","ARG", "App", "OTT", "T2G", "Total")
```

```{r}
PGAStats <-
  read.table(file ="PGA_Stats.txt", header = FALSE,sep = "\n",dec = ".", skip = 1, quote = "")

PGAStats <- as.data.frame(matrix(PGAStats$V1[PGAStats$V1!=""], ncol = 9, byrow = TRUE))

names(PGAStats) <- c("Position","Player", "Score","Putt","ARG", "App", "OTT", "T2G", "Total")
```

```{r}
SchwabStats <-
  read.table(file ="Schwab_Stats.txt", header = FALSE,sep = "\n",dec = ".", skip = 1)

SchwabStats <- as.data.frame(matrix(SchwabStats$V1[SchwabStats$V1!=""], ncol = 9, byrow = TRUE))

names(SchwabStats) <- c("Position","Player", "Score","Putt","ARG", "App", "OTT", "T2G", "Total")

```

#### Join stats and fantasy tables and rbind all tournaments together
```{r}
Memorial <-
  MemorialStats %>%
  left_join(MemorialFantasy, by =  c(Player = "Name"))
PGA <-
  PGAStats %>%
  left_join(PGAFantasy, by = c(Player = "Name"))
Schwab <-
  SchwabStats %>%
  left_join(SchwabFantasy, by = c(Player = "Name"))

Tournaments <- rbind(Memorial, PGA, Schwab)

Tournaments$Score <-
  ifelse(Tournaments$Score == "E", 0, Tournaments$Score)
```

```{r}
#tournplayed column
TournPlayed <-
  Tournaments %>%
  group_by(Player) %>%
  summarise(count = n()) %>%
  rename(tournplayed = count)
Tournaments <-
  Tournaments %>%
  left_join(TournPlayed)
```
```{r}
#MadeCut column
Tournaments <-
  Tournaments %>%
  mutate(Tournaments, MadeCut = (ifelse(Position == "CUT", "No", "Yes")))
```

```{r}
#getting tournaments into their own columns for each player
CharlesSchwabSpread <-
  Tournaments %>%
  filter(Tournament == "Charles Schwab") %>%
  spread(Tournament, Score) %>%
  select(Player, 'Charles Schwab')
MemorialSpread <-
  Tournaments %>%
  filter(Tournament == "Memorial") %>%
  spread(Tournament, Score) %>%
  select(Player, Memorial)
PGASpread <-
  Tournaments %>%
  filter(Tournament == "PGA Championship") %>%
  spread(Tournament, Score) %>%
  select(Player, 'PGA Championship')

Tournaments <-
  Tournaments %>%
  left_join(CharlesSchwabSpread, by = c(Player = "Player"))
Tournaments <-
  Tournaments %>%
  left_join(MemorialSpread, by = c(Player = "Player"))
Tournaments <-
  Tournaments %>%
  left_join(PGASpread, by = c(Player = "Player")) 
```

```{r}
#Average, changing tournament scores to numeric type
Tournaments[,16] <- as.integer(Tournaments[,16])
Tournaments[,17] <- as.integer(Tournaments[,17])
Tournaments[,18] <- as.integer(Tournaments[,18])
Tournaments$avg <- round(rowMeans(Tournaments[,16:18], na.rm=TRUE), 1)

```


```{r}
#rank column
filterpattern <- "(T(\\d+)|(\\d+))"
rankpattern = "(\\d+)"
Tournaments <-
  Tournaments %>%
  mutate(rank = ifelse(grepl(filterpattern, Position), (as.numeric(str_extract(Position, rankpattern))), NA))

#top 10 column
Tournaments <-
  Tournaments %>%
  mutate(top10 = ifelse(Tournaments$rank <= 10, "Yes", "No"))
```

```{r}
#Salary Range
Tournaments$Salary = as.numeric(Tournaments$Salary)
Tournaments$SalaryRange <-paste((as.character(signif(Tournaments$Salary, 1))), "s",sep = "")
```

```{r}
#order columns
Tournaments <- 
  Tournaments[c(1,2,3,4,5,6,7,8,9,10,11,12,13,20,21,15,22,14,16,17,18,19)]
```


